language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-frontendler' ]; then cd .. && eval "mv $currentfolder generator-frontendler" && cd generator-frontendler; fi

